# Generated by Django 3.2.5 on 2021-11-03 19:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 3, 19, 21, 16, 393342, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 11, 3, 19, 21, 16, 393342, tzinfo=utc))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
