# Generated by Django 3.2.5 on 2021-11-04 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20211104_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 16, 46, 36, 137569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 16, 46, 36, 137569, tzinfo=utc)),
        ),
    ]
